# Introduction to Python - Autonomous Driving Software Engineering

For illustrative purposes, this tutorial is made in an IPython-Notbebook (`.ipynb`-file). All coding-related aspects in this notebook are relevant for standard programming in `Python`.

Run cells with `Shift + Enter`

## 1. Why Python? 

First of all, before learning a new programming language, it is important to be aware of its characteristics:

`Python` is entirely **free** to use and distribute due to its open-source license. There are numerous **tools, libraries, and packages** for `Python` that cover many scientific subjects, such as data-science, image-processing, and motion-planning in autonomous driving, to name a few. Furthermore, `Python` is **easy to learn, read and write** due to its syntax close to the English language. Compared to other programming languages, such as C/C++, `Python` is **interpreted** instead of compiled. This means that Python code is **executed line by line**.  For this and a few other reasons that increase the convenience while programming, `Python` is significantly **slower** during runtime, compared to e.g. C++. However, all these aspects substantially increase the **productivity** in development and allow you to focus on the **scientific part of a problem**, instead of the programming part. Lastly, like C/C++, many languages require you to change your code depending on your platform (Windows/macOS/Linux). For `Python`, however, you generally only write your code once (except for system-dependent features) and run it on **any platform**.

`Python` will mostly not operate safety- and time-critical modules of a system. However, it will be the right choice for **prototyping** and creating a **proof of concept** for you as an engineer.

## 2. Structure of Python

### 2.1 Python Scripts, Modules and Packages

`Python` code is usually in the form of **scripts** or **modules**, both with the same file-ending `.py`. There is **no internal distinction** between `Python` scripts and modules - both are executable and importable, although modules, mostly contained in library code, often won't do anything when executed directly. The difference lies in their structure.

Let's look at the following two file examples without emphasising too much on the exact functionality and coding details:

<div class="row">
  <div class="col-md-5" markdown="1">
  
  ```python
      
  # functionality_module.py
  def certain_functionality(data_struct):
    # do something with input 
    return other_data_struct
      
      
  # vizualization_module.py
  def vizualize_data(data_struct): 
    # do something with input 
      
  ```
      
  </div>
    
  <div class="col-md-7" markdown="1">
      
  ```python
      
  # script.py
  from functionality_module import certain_functionality
  from vizualization_module import vizualize_data
        
  # Prototyping, vizualizing, testing, ...  
  result_1 = certain_functionality(some_data)
  result_2 = certain_functionality(other_data)

  vizualize_data(result_1)
  vizualize_data(result_2)
      
  # Export results 

  ```
      
  </div>
</div>

The upper example is aiming to illustrate, that functions and variables can be **encapsuled** in modules. Like this, we can **modularly** use any function and prevent duplicate code in our **script** that runs from top to bottom. Modules are parts of **libraries**. Libraries on the other hand are included in **packages** that can be downloaded using tools such as `pip` or `Anaconda`.



### 2.2. IPython-Notebooks

IPython-Notebooks represent an extension to regular `Python` files. IPython-Notebooks, such as this one, are made up of several cells and can be used similar to standard `Python` scripts with optional documentation. Each cell can contain either `Python` code or Markdown text. Yet, don't worry about coding details. Everything will be explained in chapter 3 - Python 3 Basics.

You can execute cells by clicking on it and pressing `Shift` + `Enter`. Check out the following examples:

In [1]:
L = [5, 4, 3, 2, 1, 0]

print(L[3] + 5)

7


As global variables are shared between cells, we can acces `L` in the next cell

In [2]:
print(L[3])

2


In [3]:
# After executing this cell, try and re-execute the upper cell
L = ["Pedestrian", "Byciclist", "Car", "Truck"]

Make sure to **save your changes** with `Strg` + `S` after editing cells!

## 3. Python 3 Basics 

### 3.1. Hello World!

In almost every programming tutorial, the very first step is to write a "Hello-World" program. In `Python`, this is easily done in only one line! We simply use the `print`-statement as follows:

In [4]:
print("Hello World")

Hello World


For those of you who are familiar, you can compare this with the tedious implementation of "Hello World" in `C++`:

```c++

# include <iostream>

int main() 
{
    std::cout << "Hello World!";
    return 0;
}

```

` Output: Hello World! ` 

### 3.2. Variables and Types

Python is completely object oriented and dynamic. Variables don't need to be declared before assigning values. However, there are different types of variables:

#### 3.2.1. Integers

In [5]:
my_int = 9
print(my_int)

9


#### 3.2.2. Floating point numbers

In [6]:
my_float = 9.4
print(my_float)

9.4


`Python` even converts integers to floating point numbers when operating with both. If you want to change the datatype of your variables you can use `casting` operators:

In [7]:
# Python interpreter converts my_int to floating point number
print(my_float - my_int)

# Casting my_float to an intgeger value (numbers are rounded down)
my_casted_int = int(my_float)
print(my_casted_int - my_int)

0.40000000000000036
0


#### 3.2.3. Strings 

Strings are either defined with single or double quotes `'', ""`:

In [8]:
my_first_string = "Autonomous"
my_second_string = "Driving"

print(my_first_string + " " + my_second_string)

Autonomous Driving


#### 3.2.4. Lists

Lists in `Python` are similar to arrays from other programming languages. They can contain **any** type of variables:

In [9]:
# Initializing list with square brackets []
my_list = [2, 3, 4]
print(my_list)

# values can be appended to the list via .append()
my_list.append(5)
print(my_list)

# You can access a value over its index (starting at 0)
print(my_list[3])

[2, 3, 4]
[2, 3, 4, 5]
5


### 3.3. Basic Operators

#### 3.3.1. Arithmetic Operators

Addition (+), substraction (-), multiplication(*), and division (/) are standard operators for numbers:

In [10]:
my_float = 1.0 + 2.0 * 3.0 / 4.0
print(my_float)

my_float += 1.0  # This is the same as my_float = my_float + 1.0
print(my_float)

my_float *= 3.0  # This is the same as my_float = my_float * 3.0
print(my_float)

2.5
3.5
10.5


The modulo operator (%) returns the integer remainder of a division:

In [11]:
remainder = 11 % 3
print(remainder)

2


A power relationship is realized using two multiplication symbols (**):

In [12]:
squared_number = 4 ** 2
cubed_number = 4 ** 3
print(squared_number)
print(cubed_number)

16
64


Several other operators, such as square root, are part of math-heavy packages such as `numpy`.

### 3.4. Conditions

Python uses boolean logic (`True` or `False`) to evaluate conditions. Check out the follwing examples:

In [13]:
x = 1

print(x == 1)
print(x != 1)
print(x != 2)

True
False
True


#### 3.4.1 If, elif, else, and, or, in, is, not 

As previously mentioned, `Python` has several English-like elements. Especially when evaluating certain expressions, wether something is `True` or `False`, we can use these as follows:

In [14]:
Lecture = "ADSE"
List_of_Lectures = ["ADSE", "AI"]

if Lecture == "ADSE":
    print(Lecture + " is a very interesting lecture!")

ADSE is a very interesting lecture!


In [15]:
if Lecture in List_of_Lectures:
    print(Lecture + "is taught at the FTM")

ADSEis taught at the FTM


In [16]:
statement = False

if statement is False:
    print("This statement is false")

This statement is false


In [17]:
if statement is not True:
    print("This statement is not true")

This statement is not true


In [18]:
if statement is True:
    print("This statement is true")
elif statement is False:
    print("This statement is false")  # This line is being executed

This statement is false


In [19]:
if statement is True:
    print("This statement is true")
else:
    print("This statement is not true")  # This line is being executed

This statement is not true


In [20]:
# Note that we get a Warning when comparing values against a certain value with "is"
# This is because the 'is' operator is not matching the values of the variables, but the instances themselves
# Here we should use '==' instead of 'is'

print(1 == 1.0)
print(1 is 1.0)

True
False


<>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-20-a68fccb5a7e9>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(1 is 1.0)


### 3.5. Loops

In [21]:
values = [3, 1, 2, 8, 2, 5]

#### 3.5.1. "for" loop

for-loops are the basic method to iterate over lists:

In [22]:
for v in values:
    print(v)

3
1
2
8
2
5


During every iterations the variable `v` is being assigned the current value of the list `values`.

Special functions, such as `range()` and `len()`, are sometimes useful when using for-loops:

In [23]:
for v in range(4):
    print(v)

0
1
2
3


In [24]:
for v in range(2, 4):
    print(v)

2
3


In [25]:
for v in range(len(values)):
    print(v)

0
1
2
3
4
5


Lastly, another useful function, especially when iterating over datasets, is the `enumerate()` function that we can use as follows:

In [26]:
# the enumerate operator returns index and value of a list in a for loop

for index, value in enumerate(values):
    print("index: " + str(index) + ", value: " + str(value))

index: 0, value: 3
index: 1, value: 1
index: 2, value: 2
index: 3, value: 8
index: 4, value: 2
index: 5, value: 5


#### 3.5.2. "while" loop

while-loops iterate until the boolean condition (`True` or `False`) at the top is not met:

In [27]:
value = 0

while value <= 3:
    print(value)
    value += 1

0
1
2
3


#### 3.5.3 "break" and "continue" statements

`break` and `continue` are methods to exit and skip the current block of a loop. Check out the examples:

In [28]:
value = 0

while True:  # Will never exit the loop unless we exit somehow
    print(value)
    value += 1
    if value >= 3:
        break

0
1
2


In [29]:
for v in range(7):
    if v % 2 == 0:
        continue
    print(v)

1
3
5


### 3.6 Functions

Functions are a convenient way to modularize individual code blocks and introducing a structure in your software. Dividing your code into different parts improves readability, especially when using concise function names. It saves a lot of time and is the fundamental way to define interfaces, especially when working in a team. 

A function always starts with the keyword `def`:

In [30]:
def function(
    input_structure,
):  # it is common practice to use lowercase letters for functions
    pass

The upper function defines a function with the name `function` and an input. Until now the input datatype is not set.

Similar to if-else conditions and loops, code within the function is always indented one block. Also, if we don't yet intend to write any code in the function, we have to use the keyword `pass`.

A function doesn't need input such as the following one:

In [31]:
def hello_world():
    print("Hello World!")

We can acces the function by it's name. dont forget the brackets `()`

In [32]:
hello_world()

Hello World!


A function can also have a return value such as the following one:

In [33]:
def highest_number_of_list(L):

    highest_number = None
    # variables must be initialized in the same / or a superordinate block.
    # Otherwise we can't acces them later on.

    for value in L:

        if highest_number is None:
            highest_number = value

        elif value > highest_number:
            highest_number = value

    return highest_number

Now we can again acces the function by it's name. However, we must assign the return value to another variable or directly use it.

In [34]:
numbers = [1, 9, 4, 5, -12]

x = highest_number_of_list(numbers)

print(x)

9


## 4. Classes and Objects (Object Oriented Programming)

As already mentioned in chapter 2.1., Python modules are aiming to modularize code and encapsule variables and functions. To realize this, **packages** commonly us **classes**. Classes are an encapsulation of variables and functions into a single **entity**. **Objects** are instances from classes and get their variables and functions, also called methods, from their class. 

Check out the following very basic class:

In [35]:
class Engineer:  # it is common practice to use uppercase letters for classes

    name = "no_name"

    def description():
        print(name + " is an Engineer!")

We can now generate an instance/object of this class and acces the variables and methods/functions with the `.` operator as the follwing:

In [36]:
eng = Engineer

eng.description()

NameError: name 'name' is not defined

Unfortunately, the variable `name` is not yet accesible from the method `description`.

To be able to acces class-variables from a function, we have to use the `self` parameter. `self` is needed, because whenever an object calls its own method, the object itself has to be passed as the first argument. Let's modify our class for this purpose:

In [37]:
class Engineer:
    def __init__(self):
        self.name = "no_name"

    def description(self):
        print(self.name + " is an Engineer!")

In [38]:
eng = Engineer()
eng.name = "Stefanie"

If we now want to print the description of our object, we have to again call `eng.description()`. Using the `self` parameter, the expression `eng.description()` can be interpreted as `Engineer.description(eng)`:

In [39]:
eng.description()

Stefanie is an Engineer!


The `__init__` method is part of every class and is called as soon as an object of a class is instantiated. The method can be used to initialize its object in some way. Note the double underscores at both the beginning and end of the name.

We can also use the `__init__` method to hand over certain variables when instantiating our new object. For this we again need to modify our class as the following:

In [40]:
class Engineer:
    def __init__(self, name):
        self.name = name

    def description(self):
        print(self.name + " is an Engineer!")

In [41]:
eng = Engineer("Stefanie")

eng.description()

Stefanie is an Engineer!


Notice that we only handed over one variable to our object when instantiating. `self` is automatically handed over to our new object so we don't explicitly do this.

## 5. Packages
### 5.1. Imports

Every `Python` module or script usually starts with important imports of **packages**. `Anaconda` and, `Python` in general, comes with several preinstalled packages. However, we have to execute the following import cell before running any package related code:

In [42]:
import os
import time
import numpy as np
import cv2 as cv
import torch
import matplotlib.pyplot as plt

The keyword `as` allows to use aliases for package-names, which can be very useful when trying to write compact code.

### 5.2. Numpy

`numpy` is a high performance framework for operations on multi-dimensional arrays.

Now, let's create a simple `(2, 4)` numpy array:

In [43]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

We can check the data type and shape of this array:

In [44]:
print(a)
print(a.dtype)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
int32
(2, 4)


Often we want to initialize an array with a fixed size, such as the following two:

In [45]:
zeros = np.zeros([2, 2], dtype=int)
ones = np.ones([4], dtype=int)

print(zeros)
print(ones)

[[0 0]
 [0 0]]
[1 1 1 1]


We can slice the array and save e.g. the first two colums in a new array:

In [46]:
b = a[:, :2]
print(b)
print(b.shape)

[[1 2]
 [5 6]]
(2, 2)


We can similarly save the first row of array `b` in another new array:

In [47]:
c = b[:1, :]
print(c)
print(c.shape)

[[1 2]]
(1, 2)


We can select elements of an array which satisfy a condition: 

In [48]:
mask = a <= 6
d = a[mask]
print(d)

[1 2 3 4 5 6]


Finally, let's check out some mathematical operations:

In [49]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


Elementwise sum. Both produce the same array:

In [50]:
print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


Elementwise difference. Both produce the same array:

In [51]:
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


Elementwise product. Both produce the same array:

In [52]:
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [53]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Elementwise sqare root and exponential operation:

In [54]:
print(np.sqrt(x))
print(np.exp(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


And finally the dot-product between Matrices/Vectors. In the case of 2 vectors with dimensions `(1, 2)` and `(2, 1)` the output is a scalar:

In [55]:
# print(x[:1, :])
# print(y[:, :1])

print(np.dot(x[:1, :], y[:, :1]))

print(x[:1, :] @ y[:, :1])

print(np.matmul(x[:1, :], y[:, :1]))

[[19]]
[[19]]
[[19]]


For more information, please take a look at https://numpy.org/doc/stable/numpy-user.pdf for further reference.

### 5.3. OpenCV

`OpenCV` is a very popular open-source library for computer vision. 

In the following we will check out a few functionalities of `OpenCV`. Let's start with the basics by importing and visualizing an image:

In [56]:
import cv2 as cv
import numpy as np

In [ ]:
img = cv.imread("./src/car.png")

cv.imshow("image", img)
cv.waitKey(0)
cv.destroyAllWindows()

Click on the image and press any key to close it and continue. It might appear in the __background__. However, __Don't click on the red cross__. If Jupyter crashes, __restart the Kernel__. Don't forget the import `OpenCV` again.

In `OpenCV` images are stored as matrices. In our case, we have a matrix of size `Height x Width x Channels = 165x230x3` which is color-coded as BGR by default. Let's quickly change the color space from BGR to HSV:

<img src="./src/HSV_cone.png" width="250"> <img src="./src/HueScale.svg" width="300">

For HSV, the hue range is `[0,179]` instead of `[0, 359]` (memory issues), saturation range is `[0,255]`, and value range is `[0,255]`. 

In [ ]:
hsv_image = cv.cvtColor(img, cv.COLOR_BGR2HSV)

Basic image-processing operations, such as colorfiltering are easily done in the HSV colorspace. We are going to define a filtermask for blue colors and apply it to the image. We are also going to make use of `NumPy`:

In [ ]:
# Define range of blue color in HSV.
# Remember that the Hue Range is only [0,179]
lower_blue = np.array([170 / 2, 0, 0], dtype=int)
upper_blue = np.array([200 / 2, 255, 255], dtype=int)

# Threshold the HSV image to get only blue colors
mask = cv.inRange(hsv_image, lower_blue, upper_blue)

# Bitwise-AND mask and original image
filtered = cv.bitwise_and(hsv_image, hsv_image, mask=mask)

# Convert back to BGR
res = cv.cvtColor(filtered, cv.COLOR_HSV2BGR)

cv.imshow("image", res)
cv.waitKey(0)
cv.destroyAllWindows()

OpenCV (Open Source Computer Vision Library: http://opencv.org) is an open-source library that includes several hundreds of computer vision algorithms. For further reference, please visit https://docs.opencv.org/master/d6/d00/tutorial_py_root.html 

### 5.4. SciPy


### 5.5. PyTorch

## 6. Virtual environments

You may have noticed, that the first thing we have done in `Anaconda` was to set up an environment for the assignments. The purpose of such a (virtual) environment is to have space where packages, which are specefic to a certain project, can be installed. Like this we ensure that we are not getting in trouble with package dependencies. Lets think about the following scenario without any virtual environment: 



![title](./src/no_virtual_environments.png)

We have two different projects on our computer that partially use the same packages. Project A is several months older and uses older versions of the shared packages than Project B. We now run into problems as we don't know the exact versions of our computer's installed packages. Suppose we update our packages; the older versions are probably overwritten. We don't want to mess things up and create environments for each project and its packages:

![title](./src/virtual_environments.png)

Once we have set up something, we now don't need to worry about any dependencies anymore.

## Sources

Python Basics: https://www.learnpython.org/

Numpy: https://numpy.org/doc/stable/numpy-user.pdf

OpenCV: https://docs.opencv.org/master/d6/d00/tutorial_py_root.html

PyTorch: https://pytorch.org/docs/stable/index.html